from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .core import AgentResult, BaseAgent


class ReasoningAgent(BaseAgent):
    """
    Produces a clinical reasoning report from the outputs generated by
    previous agents.
    """

    def __init__(self) -> None:
        super().__init__("ReasoningAgent")

    def execute(self, context: dict[str, Any]) -> dict[str, Any]:
        results = context.get("results", [])

        report = {
            "summary": self._build_summary(results),
            "confidence": self._assess_confidence(results),
            "explainability": self._assess_explainability(results),
            "recommendation": self._build_recommendation(results),
        }

        output_dir = (
            Path(context["project_root"])
            / "results"
        )
        output_dir.mkdir(parents=True, exist_ok=True)

        output_path = output_dir / "clinical_reasoning.json"

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=4)

        return {
            "report_path": str(output_path),
            "report": report,
        }

    def _build_summary(
        self,
        results: list[Any],
    ) -> str:
        if not results:
            return "No agent outputs available."

        completed = [
            r.name
            for r in results
            if getattr(r, "status", "") == "completed"
        ]

        if not completed:
            return "No completed agent outputs."

        return (
            "Clinical reasoning generated using: "
            + ", ".join(completed)
        )

    def _assess_confidence(
        self,
        results: list[Any],
    ) -> str:
        for result in results:
            payload = getattr(result, "payload", {})

            if isinstance(payload, dict):
                value = payload.get("confidence")

                if value is not None:
                    try:
                        score = float(value)

                        if score >= 0.90:
                            return "High"

                        if score >= 0.70:
                            return "Moderate"

                        return "Low"

                    except Exception:
                        pass

        return "Unknown"

    def _assess_explainability(
        self,
        results: list[Any],
    ) -> str:
        for result in results:
            payload = getattr(result, "payload", {})

            if isinstance(payload, dict):
                if (
                    "shap_summary_path" in payload
                    or "shap_plot_path" in payload
                    or "explanation" in payload
                ):
                    return "SHAP explanations available."

        return "No explainability outputs found."

    def _build_recommendation(
        self,
        results: list[Any],
    ) -> str:
        confidence = self._assess_confidence(results)

        if confidence == "High":
            return (
                "Prediction confidence is high. "
                "Review alongside clinical findings before diagnosis."
            )

        if confidence == "Moderate":
            return (
                "Prediction confidence is moderate. "
                "Consider additional clinical review."
            )

        if confidence == "Low":
            return (
                "Prediction confidence is low. "
                "Recommend manual ECG interpretation."
            )

        return (
            "Insufficient information to generate a recommendation."
        )

    def run(
        self,
        context: dict[str, Any],
    ) -> AgentResult:
        return super().run(context)

